### ISSUE TITLE
Stage1 tool  passes SimTelEventsource traitlet to all event sources

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1383]
When trying to read LST data with the dl1 tool, it passes a traitlet that only the `SimTelEventSource` has (not the public API of EventSource`) to it:

```
❯ ctapipe-stage1-process --input LST-1.4.Run01834.0000.fits.fz --output LST-1.4.Run01834.0000.dl1.h5INFO [Stage1ProcessorTool] (tool/initialize): ctapipe version 0.8.0.post11+gita62e121
INFO [Stage1ProcessorTool] (tool/run): Starting: ctapipe-stage1-process
ERROR [Stage1ProcessorTool] (tool/run): Caught unexpected exception: Traitlet does not exist: gain_selector
Traceback (most recent call last):
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/core/tool.py", line 215, in run
    self.setup()
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/tools/stage1.py", line 258, in setup
    EventSource.from_config(parent=self, gain_selector=self.gain_selector)
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 337, in from_config
    return event_source(config.EventSource.input_url, config=config, **kwargs)
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 34, in event_source
    return EventSource.from_url(input_url, **kwargs)
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 295, in from_url
    return subcls(input_url=input_url, **kwargs)
  File "/home/maxnoe/Uni/CTA/ctapipe_io_lst/ctapipe_io_lst/__init__.py", line 118, in __init__
    super().__init__(**kwargs)
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 142, in __init__
    super().__init__(config=config, parent=parent, input_url=input_url, **kwargs)
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/core/component.py", line 113, in __init__
    raise TraitError(f"Traitlet does not exist: {key}")
traitlets.traitlets.TraitError: Traitlet does not exist: gain_selector
INFO [Stage1ProcessorTool] (tool/run): Output: /home/maxnoe/Uni/CTA/cta-lstchain/data/LST-1.4.Run01834.0000.dl1.h5```

**Comment by MaxNoe** [comment]
Fixed in #1385
