### ISSUE TITLE
ctapipe doesn't work with astropy 3.2

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1554]
We have in our requirements astropy>3, but testing it with 3.2.3, it fails during `from ctapipe import containers`, due to the NAN_TIME variable:

```python3
>>> NAN_TIME = Time(np.ma.masked_array(np.nan, mask=True), format="mjd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kkosack/miniconda3/envs/astropy3/lib/python3.8/site-packages/astropy/time/core.py", line 398, in __init__
    self._init_from_vals(val, val2, format, scale, copy,
  File "/Users/kkosack/miniconda3/envs/astropy3/lib/python3.8/site-packages/astropy/time/core.py", line 462, in _init_from_vals
    self._time.jd2[mask] = np.nan
```

Instead, using
```
>>> NAN_TIME = Time(np.ma.masked_array([np.nan,], mask=True), format="mjd")
```
seems to work for that version (haven't checked if that breaks the IO though), but might be better to just bump the version requirement in setup.py. 

It's not a critical issue,  but it does create some issues in *protopipe* if we want to mix ctapipe and an older version of gammapy that requires astropy=3.2.

**Comment by maxnoe** [comment]
Yes, please just require astropy 4
