### ISSUE TITLE
graphviz installation for the flow system GUI

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#164]
The graphviz conda package is no Python package. It simply puts the graphviz files into your virtual env's Library directory. Look e.g. for dot in the ~/anaconda/env/cta/bin/ directory.

And missing of python graphviz library it breaks most commands like ctapipe-info.  That package should be made a dependency.

[sapmcw8] ~/Projects/CTA/Working/ctapipe % ctapipe-info --tools   git:(master|)

*** ctapipe tools ***

the following can be executed by typing ctapipe-<toolname>:

Traceback (most recent call last):

  File "/Users/kosack/anaconda/envs/cta/bin/ctapipe-info", line 9, in <module>

    load_entry_point('ctapipe', 'console_scripts', 'ctapipe-info')()

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/tools/info.py", line 25, in main

    info(**vars(args))

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/tools/info.py", line 40, in info

    _info_tools()

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/tools/info.py", line 71, in _info_tools

    scripts = get_all_descriptions()

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/tools/utils.py", line 76, in get_all_descriptions

    module = importlib.import_module(info.module_name)

  File "/Users/kosack/anaconda/envs/cta/lib/python3.5/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 986, in _gcd_import

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 662, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/flow/gui/guiflow.py", line 4, in <module>

    from ctapipe.flow.gui.main_window import ModuleApplication

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/flow/gui/main_window.py", line 6, in <module>

    from ctapipe.flow.gui.graphwidget import GraphWidget

  File "/Users/kosack/Projects/CTA/Working/ctapipe/ctapipe/flow/gui/graphwidget.py", line 1, in <module>

    from graphviz import Digraph

ImportError: No module named 'graphviz'

**Comment by jacquemier** [comment]
graphviz need to be installed thanks to pip
pip install graphviz.
Doc need to be update

**Comment by jacquemier** [comment]
Close by PULL REQUEST #165
