### ISSUE TITLE
ctapipe-merge fails with --allowed-tels

### ISSUE THREAD

**Issue by nbiederbeck** [cta-observatory/ctapipe#1711]
using the conda install with v0.11 

`ctapipe-merge gamma-diffuse/gamma_20deg_0deg_run{3500,3695}*.h5 --output merged/gamma-test-paranal.dl1.h5 --progress --overwrite --allowed-tels 1`
```
2021-05-11 09:10:36,213 WARNING [ctapipe.ctapipe-merge] (dl1_merge.setup): Overwriting /home/nbiederbeck/data/stage1/merged/gamma-test-paranal.dl1.h5
2021-05-11 09:10:36,359 ERROR [ctapipe.ctapipe-merge] (tool.run): Caught unexpected exception: %d format: a number is required, not str
Traceback (most recent call last):
  File "/home/nbiederbeck/cta-software/ctapipe/ctapipe/core/tool.py", line 276, in run
    self.setup()
  File "/home/nbiederbeck/cta-software/ctapipe/ctapipe/tools/dl1_merge.py", line 216, in setup
    self.allowed_tel_names = {"tel_%03d" % i for i in self.allowed_tels}
  File "/home/nbiederbeck/cta-software/ctapipe/ctapipe/tools/dl1_merge.py", line 216, in <setcomp>
    self.allowed_tel_names = {"tel_%03d" % i for i in self.allowed_tels}
TypeError: %d format: a number is required, not str
Closing remaining open files:/home/nbiederbeck/data/stage1/merged/gamma-test-paranal.dl1.h5...done
```

**Comment by HealthyPear** [comment]
Could this be the same bug?
```python

  File "/Users/michele/Applications/ctasoft/protopipe/protopipe/pipeline/utils.py", line 198, in final_array_to_use
    subarray = sim_array.select_subarray("selected_subarray", tel_ids)
  File "/Users/michele/Applications/miniconda3/envs/protopipe-dev_test/lib/python3.8/site-packages/ctapipe/instrument/subarray.py", line 313, in select_subarray
    tel_positions = {tid: self.positions[tid] for tid in tel_ids}
  File "/Users/michele/Applications/miniconda3/envs/protopipe-dev_test/lib/python3.8/site-packages/ctapipe/instrument/subarray.py", line 313, in <dictcomp>
    tel_positions = {tid: self.positions[tid] for tid in tel_ids}
KeyError: 's'
```

**Comment by HealthyPear** [comment]
oh nevermind, apparently `select_subarray` got its args changed so now it is
`subarray = sim_array.select_subarray(tel_ids,  name="selected_subarray")`
