### ISSUE TITLE
SimTelEventSource does not support reading "extracted" calibration event files

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#1927]
**Describe the bug**

After using the the `extract_calibevent` tool to get proper telescope events with ids from a simulated simulation file, the simtel event source cannot read it, since it looks for mc shower information, which is of course not there for calibration events:

**To Reproduce**

Run a file with calibration events through `extract_calibevents` and try iterating the events using the `SimTelEventSource`.

```
2022-06-03 11:58:49,933 ERROR [ctapipe.ctapipe-process] (tool.run): Caught unexpected exception: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/core/tool.py", line 350, in run
    self.start()
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/tools/process.py", line 249, in start
    for event in tqdm(
  File "/home/mnoethe/.local/conda/envs/cta-dev/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 278, in __iter__
    for event in self._generator():
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 387, in _generator
    yield from self._generate_events()
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 424, in _generate_events
    self._fill_simulated_event_information(data, array_event)
  File "/home/mnoethe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 633, in _fill_simulated_event_information
    energy=u.Quantity(mc_shower["energy"], u.TeV),
TypeError: 'NoneType' object is not subscriptable
```

**Expected behavior**

**Supporting information**
If applicable, add screenshots, logs, or a traceback to help illustrate the bug.

**Additional context**

This might need a new release of pyeventio. I am not sure how common it is to use the `extract_calibevents` tool.

**Comment by kosack** [comment]
For testing calibration algorithms, this could be useful.  I would imagine we could just check the `EventType` and don't try to fill MC info for those events.
