### ISSUE TITLE
Error in impact calculation in simtel event source due to rounding error

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/ctapipe#2075]
**Describe the bug**

Reading a file directly pointing at zenith, I get the following error when trying to iterate events:

```
Traceback (most recent call last):
  File "/home/maxnoe/Uni/CTA/pyeventio/read_photon_times.py", line 10, in <module>
    for e in f:
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/eventsource.py", line 275, in __iter__
    for event in self._generator():
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 522, in _generator
    yield from self._generate_events()
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/io/simteleventsource.py", line 573, in _generate_events
    impact_distances = shower_impact_distance(
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/reco/impact_distance.py", line 68, in shower_impact_distance
    sky_direction = altaz_to_righthanded_cartesian(
  File "/home/maxnoe/Uni/CTA/ctapipe/ctapipe/coordinates/__init__.py", line 88, in altaz_to_righthanded_cartesian
    return np.array(spherical_to_cartesian(r=1, lat=alt, lon=-az))
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/funcs.py", line 119, in spherical_to_cartesian
    sph = SphericalRepresentation(distance=r, lat=lat, lon=lon)
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 1928, in __init__
    super().__init__(lon, lat, distance, copy=copy,
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 670, in __init__
    super().__init__(*args, **kwargs)
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 230, in __init__
    attrs = [self.attr_classes[component](attr, copy=copy, subok=True)
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/representation.py", line 230, in <listcomp>
    attrs = [self.attr_classes[component](attr, copy=copy, subok=True)
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/angles.py", line 573, in __new__
    self._validate_angles()
  File "/home/maxnoe/.local/anaconda/envs/cta-dev/lib/python3.9/site-packages/astropy/coordinates/angles.py", line 594, in _validate_angles
    raise ValueError('Latitude angle(s) must be within -90 deg <= angle <= 90 deg, '
ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got 90.00000250447816 deg
```

**To Reproduce**

```
with SimTelEventSource('tests/resources/lst_with_photons.simtel.zst', focal_length_choice="EQUIVALENT") as f:

    for e in f:
        pass
```

This is the file: https://github.com/cta-observatory/pyeventio/blob/master/tests/resources/lst_with_photons.simtel.zst

**Expected behavior**

Value should be clipped to 90°.

**Comment by maxnoe** [comment]
Should we treat altitude > 90° as "looking overhead" ?

**Comment by maxnoe** [comment]
The problem is that the closest float32 value to pi/2 is larger than pi/2:

> np.float64(np.float32(np.pi/2)) > np.float64(np.pi/2)
