### ISSUE TITLE
read_hessio.py failed to display event

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/ctapipe#43]
There is a TypeError error when trying to display an event. see error log bellow

************************************************
(root)jacquem>python read_hessio.py 
/home/jacquem/workspace/CTA/cta-pipe/ctapipe/ctapipe-extra/datasets/gamma_test.simtel.gz

Input file '/home/jacquem/workspace/CTA/cta-pipe/ctapipe/ctapipe-extra/datasets/gamma_test.simtel.gz' has been opened.
I/O block extended by 744748 to 1744748 bytes

Starting run 31964
EVENT_ID:  408 TELS:  [38 47]
\============================================
n or [enter]    - go to Next event
d               - Display the event
p               - Print all event data
i               - event Info
q               - Quit
Choice: d
Displaying... please wait (this is an inefficient implementation)
	 draw cam 38...
Traceback (most recent call last):
  File "read_hessio.py", line 88, in <module>
    display_event(event)
  File "read_hessio.py", line 53, in display_event
    signals -= signals.mean()
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

gzip: stdout: Broken pipe

************************************************

**Comment by jacquemier** [comment]
It is working with last version of ctapipe
